title: sueisok
page-title: Welcome to my channel
# home-title: It's Your
description: 'Notes，Thoughts and Else'
keywords: '“自己”这个东西是看不见的，撞上一些别的什么,反弹回来，才会了解“自己”。 所以，跟很强的东西、可怕的东西、水准很高的东西相碰撞，然后才知道“自己”是什么，这才是自我 。'
url: 'https://sueisok.github.io'
nav:
  Home: /
  Tags: /tags/
  Timeline: /timeline/
  About: /about/
  reLink: /reLink/
author: true
name: sueisok
NickName: NickName
webtitle: sueisok
bio: 地标北京 有一只猫叫狗
about: true
aboutyou: "一个想写博客的菜鸡白帽子"
portraits: /assets/madara.png
honorificPrefix: '***'
image: /assets/JHON.jpg
familyname: Your family name
honorificSuffix: King
disambiguatingDescription: Your awesome description
birthPlace: Your address
birthDate: Your Date of Birth
height: XX inches
gender: Your gender
memberOf: Your awesome orgranization
nationality: Your proud nationality
jobTitle: Your Respectful Position
knowsAbout: Your awesome Skill
knowsLanguage: ''
worksFor:
  type: LocalBusiness
  name: ''
  openingHours: 'Sa-Fr 09:00-21:00'
  priceRange: $$$
  telephone:
    - +8801XXXXXXXX
    - +8801XXXXXXXXX
  image: 'https://i.imgur.com/BGBJWBq.png'
  address:
    type: PostalAddress
    addressCountry: ''
    addressLocality: ''
    addressRegion: ''
future: true
SNS: true
SNS-icon:
  mail: 'mailto:sohelahmedjony@gmail.com'
  github: 'https://github.com/JonyBepary'
  Codepen: 'https://codepen.io/sohel-ahmed-jony/#'
  Twitter: 'https://twitter.com/@JBepary'
  instagram: 'https://www.instagram.com/sohelahmedjony/'
  Facebook: 'https://facebook.com/sa.jhone'
  Google: 'https://plus.google.com/+JonyBepary'
  weixin: ''
  qq: ''
  weibo: ''
  Dribbble: ''
  zhihu: ''
  juejin: ''
  twitch: ''
permalink: '/blog/:title/'
paginate: 4
paginatepath:
  - 'page:num'
footer:
  since: 2018
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
pygmentsTheme: default
friends:
  subeen's blog: 'http://subeen.com/'
  Corey Schafer: 'http://coreyms.com/'
  C Book By knking: 'http://knking.com/books/c2/index.html'
  Python Cookbook: 'http://shop.oreilly.com/product/0636920027072.do'
  বাংলায় প্রোগ্রামিং রিসোর্সসমূহ: 'https://github.com/me-shaon/bangla-programming-resources'
  Freely available programming book: 'https://github.com/EbookFoundation/free-programming-books'
  Grokking Algorithms (Best for Beginners who want learn Algorithms): 'https://www.manning.com/books/grokking-algorithms'
disqus: true
disqus_url: 'https://jonysblog.disqus.com/embed.js'
livere: false
livere_uid: MTAyMC8zNDI2OS8xMDgwNg==
Gitment: false
Gitment_owner: ''
Gitment_repo: ''
client_id: ''
client_secret: ''
social-share: true
social-share-items:
  - facebook
  - twitter
  - google
  - linkedin
  - diandian
  - weibo
  - qq
  - wechat
  - tencent
  - douban
  - qzone
baidu: false
baidu-url: ''
google: true
google-ID: <UA-42070905-2>
color: 'rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)'
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
logo: /assets/banner.png
twitter:
  username: your_name
  card: summary
social:
  name: your_name
  links:
    - 'mailto:yourname@example.com'
    - 'https://github.com/example'
    - 'https://codepen.io/example/#'
    - 'https://twitter.com/@example'
    - 'https://www.instagram.com/example/'
    - 'https://facebook.com/example'
    - 'https://plus.google.com/+example'
webmaster_verifications:
  google: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
exclude:
  - screenshot
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - '*.Rmd'
  - .git*
  - package-lock.json
  - gulpconfig.json
